language: php
php:
  - 5.6

before_script:
    - composer self-update
    - composer install

script:
  - bin/phpunit -c app

script:
  - phpunit --coverage-text=coverage.clover --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
